apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  type: NodePort  # Exposes the service outside the cluster
  selector:
    app: todo-app # Matches the label on your deployment pods
  ports:
    - protocol: TCP
      port: 80      # The port the service listens on internally
      targetPort: 8000 # The port your container listens on
      nodePort: 30007 # A fixed port to access it from your browser